version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: attackontitan
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password123
      - DB_NAME=attackontitan
    restart: always

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
